# Generated by Django 5.2.5 on 2025-09-25 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_cart_id_alter_chathistory_id_alter_customer_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('M', 'Men'), ('W', 'Women'), ('J', 'Jwellery')], max_length=2),
        ),
    ]
