# Generated by Django 5.2.5 on 2025-09-27 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('F', 'Football'), ('C', 'Cricket'), ('J', 'Jewelry')], max_length=2),
        ),
    ]
