# Generated by Django 5.2.5 on 2025-10-05 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('M', 'Men'), ('W', 'Women'), ('J', 'Jewelry'), ('O', 'Medicine')], max_length=2),
        ),
    ]
