# Generated by Django 5.2.5 on 2025-10-09 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_product_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='user',
            new_name='seller',
        ),
    ]
