# Generated by Django 5.2.5 on 2025-10-09 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_rename_user_product_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='seller',
        ),
    ]
