# Generated by Django 5.2.5 on 2025-10-10 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_product_stock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='stock',
            new_name='quantity',
        ),
    ]
